"use client"

import { useState, useEffect } from 'react';
import { 
  UploadCloud, FileText, Target, CheckCircle2, 
  Download, RefreshCcw, AlertCircle, FileSearch, 
  Sparkles, ArrowRight, Info, Shield, Check, Zap
} from 'lucide-react';
import { motion } from 'framer-motion';
import jsPDF from 'jspdf';
import { saveResumeAnalysis } from "@/app/actions";
import { cn } from '@/lib/utils';
import ForceGraphClient from '@/components/force-graph-client';

// --- Modular Component Imports ---
import { ScoreMeter } from '@/components/resume/ScoreMeter';
import { ScoreBreakdownChart } from '@/components/resume/ScoreBreakdownChart';
import { ForensicLoader } from '@/components/resume/ForensicLoader';
import { AuditMetricSidebar } from '@/components/resume/AuditMetricSidebar';
import { AnnotatedResume } from '@/components/resume/AnnotatedResume';
import { 
  ImprovementCard, 
  RewrittenBulletItem, 
  StrategicRoadmap, 
  DetailedAnalysis 
} from '@/components/resume/AnalysisViews';

// --- Types ---

interface ScoreBreakdown {
  keyword_match: number;
  formatting: number;
  quantified_achievements: number;
  section_completeness: number;
  action_verbs: number;
}

interface Improvement {
  category: string;
  priority: 'High' | 'Medium' | 'Low';
  issue: string;
  suggestion: string;
  example?: string;
}

interface RewrittenBullet {
  original: string;
  improved: string;
}

interface ResumeSegment {
  text: string;
  label: 'impactful' | 'weak' | 'irrelevant' | 'neutral';
  comment: string;
}

interface AnalysisCheck {
  name: string;
  score: number;
  status: 'pass' | 'fail' | 'warning';
  feedback: string;
}

interface ResumeResults {
  ats_score: number;
  score_breakdown: ScoreBreakdown;
  hiring_probability: number;
  detailed_checks: AnalysisCheck[];
  critical_issues: string[];
  improvements: Improvement[];
  missing_keywords: string[];
  strong_points: string[];
  rewritten_bullets: RewrittenBullet[];
  overall_verdict: string;
  full_resume_text?: string;
  segmented_resume: ResumeSegment[];
  graph?: {
    nodes: { id: string; group: number; val: number }[];
    links: { source: string; target: string; value: number }[];
  };
}

// --- Analysis View (Dashboard) ---

interface AnalysisViewProps {
  results: ResumeResults;
  onReset: () => void;
  jobDescription: string;
}

const ResumeAnalysisDashboard = ({ results, onReset, jobDescription }: AnalysisViewProps) => {
  const handleDownloadReport = () => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;
    doc.setFontSize(22); doc.text('ATS Resume Analysis Report', margin, y); y += 15;
    doc.setFontSize(12); doc.text(`Generated by CareerSync Pro • ${new Date().toLocaleDateString()}`, margin, y); y += 10;
    doc.text(`Overall ATS Score: ${results.ats_score}/100`, margin, y); y += 10;
    doc.save(`CareerSync_ATS_Report_${results.ats_score}.pdf`);
  };

  return (
    <div className="min-h-screen bg-[#0f1117] text-white p-6 md:p-10 animate-in fade-in duration-700 relative overflow-hidden">
      {/* Background Polish */}
      <div className="absolute inset-0 bg-[url('/grid.svg')] bg-center [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))] opacity-10 pointer-events-none" />
      <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-b from-primary/5 via-transparent to-transparent pointer-events-none" />

      <div className="max-w-7xl mx-auto space-y-10 pb-20 relative z-10">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 pb-6 border-b border-white/10">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <span className="bg-primary/20 text-primary text-[10px] font-black uppercase tracking-[0.2em] px-2 py-0.5 rounded border border-primary/20 animate-pulse">Analysis Complete</span>
              {jobDescription && (
                <span className="bg-emerald-500/20 text-emerald-400 text-[10px] font-black uppercase tracking-[0.2em] px-2 py-0.5 rounded border border-emerald-500/20">JD Targeted</span>
              )}
            </div>
            <h1 className="text-4xl font-black font-outfit tracking-tighter italic">Intelligence Report</h1>
          </div>
          <div className="flex gap-4">
            <button onClick={onReset} className="px-5 py-2.5 bg-white/5 hover:bg-white/10 text-white text-xs font-black uppercase tracking-widest rounded-xl border border-white/10 transition-all flex items-center gap-2">
              <RefreshCcw className="w-4 h-4" /> Reset
            </button>
            <button onClick={handleDownloadReport} className="px-5 py-2.5 bg-primary hover:bg-primary/90 text-white text-xs font-black uppercase tracking-widest rounded-xl shadow-lg shadow-primary/20 transition-all flex items-center gap-2">
              <Download className="w-4 h-4" /> PDF Report
            </button>
          </div>
        </div>

        {results.critical_issues.length > 0 && (
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="p-6 bg-rose-500/5 border border-rose-500/20 rounded-2xl flex flex-col md:flex-row items-center justify-between gap-6 backdrop-blur-md shadow-2xl relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-rose-500" />
            <div className="flex items-center gap-5">
              <div className="w-12 h-12 bg-rose-500/10 rounded-full flex items-center justify-center border border-rose-500/20">
                <AlertCircle className="w-6 h-6 text-rose-500 animate-pulse" />
              </div>
              <div>
                <h3 className="text-[11px] font-black uppercase tracking-[0.3em] text-rose-400">Critical Audit Alerts</h3>
                <p className="text-[10px] text-white/40 font-bold italic">Immediate risk vectors detected by Forensic Engine.</p>
              </div>
            </div>
            <div className="flex flex-wrap justify-end gap-2">
              {results.critical_issues.map((issue, i) => (
                <div key={i} className="bg-black/40 text-rose-100 text-[9px] font-black uppercase tracking-widest py-2 px-4 rounded-lg border border-rose-500/20">{issue}</div>
              ))}
            </div>
          </motion.div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
          <div className="lg:col-span-3">
             <AuditMetricSidebar results={results} />
          </div>
          <div className="lg:col-span-9 space-y-16">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-8 mb-4">
              <div className="lg:col-span-5 glass-card p-10 rounded-2xl flex flex-col items-center justify-center relative overflow-hidden group min-h-[450px]">
                <ScoreMeter score={results.ats_score} />
                <p className="text-[10px] font-black text-white/40 mt-8 tracking-[0.3em] uppercase italic">Overall ATS Index</p>
                <div className="absolute inset-0 bg-gradient-to-b from-primary/5 to-transparent pointer-events-none group-hover:opacity-100 opacity-60 transition-opacity" />
              </div>
              <div className="lg:col-span-7 glass-card p-8 rounded-2xl flex flex-col min-h-[450px] relative overflow-hidden">
                 <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground mb-4 flex items-center gap-2 italic">
                   <Zap className="w-4 h-4 text-primary animate-pulse" /> Forensic Skill Constellation
                 </h3>
                 <div className="h-full w-full flex items-center justify-center relative z-10 overflow-hidden rounded-2xl bg-black/20 border border-white/5">
                   <ForceGraphClient data={results.graph} />
                 </div>
              </div>
            </div>

            <section className="glass-card p-10 rounded-2xl relative overflow-hidden group">
               <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground mb-8 flex items-center gap-2 italic">
                 <Target className="w-4 h-4 text-primary" /> Dimension Matrix Analysis
               </h3>
               <div className="h-[400px] w-full">
                 <ScoreBreakdownChart data={results.score_breakdown} />
               </div>
            </section>

            <AnnotatedResume segments={results.segmented_resume} fullText={results.full_resume_text} />
            <DetailedAnalysis checks={results.detailed_checks || []} />
            <StrategicRoadmap criticalIssues={results.critical_issues} improvements={results.improvements} />

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 pb-20">
              <div className="lg:col-span-5 space-y-10">
                <section>
                  <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground mb-6 flex items-center gap-2 italic">
                    <ArrowRight className="w-4 h-4 text-primary" /> Recommended Refinements
                  </h3>
                  <div className="space-y-4">
                    {results.improvements.map((imp, i) => <ImprovementCard key={i} improvement={imp} />)}
                  </div>
                </section>
                <section className="glass-card p-8 rounded-2xl bg-white/[0.01]">
                  <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground mb-6 flex items-center gap-2 italic">
                    <Info className="w-4 h-4 text-amber-400" /> Keyword Deficit
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {results.missing_keywords.map((keyword, i) => (
                      <span key={i} className="bg-white/5 border border-white/10 px-3 py-1.5 rounded-lg text-[10px] font-bold text-white/70 uppercase tracking-widest">{keyword}</span>
                    ))}
                  </div>
                </section>
              </div>
              <div className="lg:col-span-7 space-y-10">
                <section className="glass-card p-8 rounded-2xl space-y-4 shadow-2xl relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-primary/5 blur-3xl pointer-events-none" />
                  <div>
                    <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-white/90 mb-1 flex items-center gap-2 italic">
                      <Sparkles className="w-4 h-4 text-primary" /> Bullet Rewrite System
                    </h3>
                    <p className="text-[10px] font-bold text-white/30 italic">Forensic translation into high-velocity recruiterspeak.</p>
                  </div>
                  <div className="space-y-6">
                    {results.rewritten_bullets.map((bullet, i) => <RewrittenBulletItem key={i} bullet={bullet} />)}
                  </div>
                </section>
                <section className="glass-card p-8 rounded-2xl bg-emerald-500/[0.01]">
                  <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground mb-6 flex items-center gap-2 italic">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" /> Asset Verification
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {results.strong_points.map((point, i) => (
                      <div key={i} className="flex gap-3 items-start text-[11px] font-bold text-white/70"><CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" /><span>{point}</span></div>
                    ))}
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// --- Main Page Component ---

export default function ResumeHub() {
  const [jobDescription, setJobDescription] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [results, setResults] = useState<ResumeResults | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [dragActive, setDragActive] = useState(false);

  const handleAnalyze = async () => {
    if (!file) return;
    setIsAnalyzing(true);
    setError(null);
    try {
      const formData = new FormData();
      formData.append('resume', file);
      if (jobDescription) formData.append('jobDescription', jobDescription);
      
      const response = await fetch('/api/resume/score', { method: 'POST', body: formData });
      const data = await response.json();
      
      if (!response.ok) {
        throw new Error(data.detail || data.error || 'Forensic analysis failed');
      }
      
      setResults(data);
      await saveResumeAnalysis({
        atsScore: data.ats_score,
        content: data.full_resume_text || "",
        gaps: JSON.stringify(data.missing_keywords || []),
        fileName: file.name,
        jdSimilarity: data.jd_match_accuracy,
        jdGaps: JSON.stringify(data.jd_keyword_gaps || [])
      });
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsAnalyzing(false);
    }
  };

  if (results) {
    return <ResumeAnalysisDashboard results={results} onReset={() => setResults(null)} jobDescription={jobDescription} />;
  }

  return (
    <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center p-6 bg-[#0f1117] relative overflow-hidden">
      {/* Immersive Background */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(59,130,246,0.1),transparent_50%)]" />
      <div className="absolute inset-0 bg-[url('/grid.svg')] bg-[size:32px_32px] opacity-[0.03] pointer-events-none" />
      
      <ForensicLoader active={isAnalyzing} />
      
      <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} className="w-full max-w-4xl glass-card rounded-3xl overflow-hidden flex flex-col md:flex-row border border-white/10 shadow-3xl relative z-10 backdrop-blur-2xl">
        <div className="w-full md:w-5/12 p-10 bg-gradient-to-br from-primary/30 via-primary/10 to-transparent relative overflow-hidden flex flex-col justify-between border-r border-white/5">
          <div className="relative z-10">
            <div className="w-14 h-14 bg-primary/20 rounded-2xl flex items-center justify-center mb-6 border border-primary/30 shadow-[0_0_20px_rgba(59,130,246,0.3)]">
               <FileSearch className="w-7 h-7 text-primary" />
            </div>
            <h1 className="text-4xl font-black font-outfit tracking-tighter italic mb-4 text-white">Forensic Scanner</h1>
            <p className="text-white/40 text-[11px] font-bold uppercase tracking-widest leading-relaxed mb-8">Deploying Version 2.5 of the Deep-Audit Neural Engine.</p>
            <div className="space-y-4">
              {["15+ Years Recruiting Logic", "Action-Oriented Rewrites", "Keyword Gap Detection", "Formatting Sanity Checks"].map((item, i) => (
                <div key={i} className="flex gap-3 items-center text-[10px] font-black uppercase tracking-[0.2em] text-white/80 italic animate-in fade-in slide-in-from-left duration-1000" style={{ animationDelay: `${i * 200}ms` }}>
                   <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" /> {item}
                </div>
              ))}
            </div>
          </div>
          <div className="pt-10 flex items-center gap-3">
             <Shield className="w-5 h-5 text-primary/40" />
             <span className="text-[9px] font-black text-white/20 uppercase tracking-[0.4em]">Forensic Protocol Secured</span>
          </div>
        </div>

        <div className="w-full md:w-7/12 p-10 bg-[#0a0c10]/60">
          {error && (
            <div className="mb-6 p-4 bg-rose-500/10 border border-rose-500/20 rounded-xl flex items-center gap-3 text-rose-400 text-xs font-bold animate-in fade-in slide-in-from-top-2">
              <AlertCircle className="w-5 h-5 shrink-0" /><p>{error}</p>
            </div>
          )}
          
          <div className="space-y-8">
            <div className="space-y-3">
               <label className="text-[9px] font-black uppercase tracking-[0.3em] text-primary italic">Target Job Description</label>
               <textarea 
                 value={jobDescription}
                 onChange={(e) => setJobDescription(e.target.value)}
                 placeholder="Paste target JD to calibrate the scanner..."
                 className="w-full h-32 bg-white/[0.02] border border-white/5 rounded-xl p-4 text-xs font-medium focus:border-primary/50 focus:bg-white/[0.05] transition-all outline-none resize-none placeholder:text-white/5 scrollbar-none"
               />
            </div>

            <div className="space-y-3">
              <label className="text-[9px] font-black uppercase tracking-[0.3em] text-primary italic">Career Source Material</label>
              <div 
                onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
                onDragLeave={() => setDragActive(false)}
                onDrop={(e) => { e.preventDefault(); setDragActive(false); if (e.dataTransfer.files?.[0]) setFile(e.dataTransfer.files[0]); }}
                className={cn(
                  "border-2 border-dashed rounded-2xl p-10 flex flex-col items-center justify-center transition-all cursor-pointer group relative overflow-hidden h-44",
                  file ? "border-emerald-500/40 bg-emerald-500/5 shadow-[0_0_30px_rgba(16,185,129,0.1)]" : "border-white/5 hover:border-primary/40 hover:bg-white/5",
                  dragActive && "border-primary bg-primary/5"
                )}
                onClick={() => document.getElementById('file-upload')?.click()}
              >
                <input id="file-upload" type="file" className="hidden" accept=".pdf" onChange={(e) => e.target.files?.[0] && setFile(e.target.files[0])} />
                {file ? (
                  <div className="text-center animate-in zoom-in duration-500">
                    <div className="w-12 h-12 bg-emerald-500/20 rounded-full flex items-center justify-center mb-3 mx-auto shadow-[0_0_15px_rgba(16,185,129,0.3)]">
                      <Check className="w-6 h-6 text-emerald-500" />
                    </div>
                    <p className="text-sm font-black font-outfit text-white tracking-tight">{file.name}</p>
                    <p className="text-[8px] text-emerald-500/60 font-black uppercase mt-1 tracking-widest italic">Signal Integrity Locked</p>
                  </div>
                ) : (
                  <div className="text-center group-hover:scale-105 transition-transform duration-500">
                    <UploadCloud className="w-10 h-10 text-white/5 mb-4 mx-auto group-hover:text-primary transition-colors" />
                    <p className="text-xs font-black text-white/40 uppercase tracking-widest">Drop Resume / Select Vector</p>
                    <p className="text-[8px] text-white/10 font-black uppercase mt-2 tracking-[0.3em]">PDF Engine V2.5 • Max 5MB</p>
                  </div>
                )}
              </div>
            </div>

            <button 
              onClick={handleAnalyze}
              disabled={!file}
              className="w-full py-4 bg-primary hover:bg-primary/90 disabled:bg-white/5 disabled:text-white/5 text-white text-[10px] font-black uppercase tracking-[0.4em] rounded-xl transition-all shadow-2xl shadow-primary/30 flex items-center justify-center gap-4 group relative overflow-hidden"
            >
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full group-hover:animate-[shimmer_2s_infinite]" />
              <Target className="w-5 h-5 group-hover:rotate-45 transition-transform duration-500" />
              Initialize Scan
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
